name: Publish to Cocoapods

on:
  repository_dispatch:
    types:
      - cocoapods-deploy

jobs:
  publish:
    name: Swift 5.3 on ubuntu-latest
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}
            submodules: true
      - uses: swift-actions/setup-swift@v1
      - name: Get swift version
        run: swift --version
      - name: Run tests
        run: swift test