name: Publish to Cocoapods

# on:
#   repository_dispatch:
#     types:
#       - cocoapods-deploy
on: 
  push: 
    branches: master

permissions: write-all

jobs:
  publish:
    name: Download build files and publish to cocoapods
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and unzip artifact and push to master
        run: |
          # Get the latest workflow run
          curl -s -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/aditya-likeminds/LikeMinds-iOS-Feed-SDK/actions/runs > run_info.json
      
          # Extract the run ID
          export RUN_ID=$(cat run_info.json | jq -r '.workflow_runs[0].id')
      
          # Get information about the artifacts in the latest run
          curl -s -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/aditya-likeminds/LikeMinds-iOS-Feed-SDK/actions/runs/${RUN_ID}/artifacts > artifact_info.json
      
          # Get the URL for the artifact archive
          export ARTIFACT_URL=$(cat artifact_info.json | jq -r '.artifacts[0].archive_download_url')
      
          # Download and extract the artifact
          curl -LJO -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            $ARTIFACT_URL
      
          unzip -qo '*.zip'

          ls -al
      
      - run: cp LikeMindsFeed.podspec LikeMindsFeed.xcframework /home/runner/work/LikeMinds-iOS-Feed-SDK-Public/LikeMinds-iOS-Feed-SDK-Public/
        env:
          PAT: ${{ secrets.PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - run: |
          ls -al

          # Configure Git
          git config --global user.name "$(git log -n 1 --pretty=format:%an)"
          git config --global user.email "$(git log -n 1 --pretty=format:%ae)"

          # Add, commit, and push changes
          git add LikeMindsFeed.podspec LikeMindsFeed.xcframework
          git commit -m "Update artifacts from GitHub Actions run ${RUN_ID}"
          git push origin master
        env:
          PAT: ${{ secrets.PAT }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}