name: Publish to Cocoapods

on:
  repository_dispatch:
    types:
      - cocoapods-deploy

jobs:
  publish:
    name: Download build files and publish to cocoapods
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download artifact
        id: download-artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.PAT}}
          # Optional, workflow file name or ID
          # If not specified, will be inferred from run_id (if run_id is specified), or will be the current workflow
          workflow: build.yml
          # Optional, uploaded artifact name,
          # will download all artifacts if not specified
          # and extract them into respective subdirectories
          # https://github.com/actions/download-artifact#download-all-artifacts
          # is treated as a regular expression if input name_is_regexp is true
          # will download only those artifacts with a name that matches this regular expression
          # https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_expressions
          name: xcframework-build
          # Optional, a directory where to extract artifact(s), defaults to the current directory
          # path: extract_here
          # Optional, defaults to current repo
          repo: "https://github.com/aditya-likeminds/LikeMinds-iOS-Feed-SDK"
          # Optional, check the workflow run to whether it has an artifact
          # then will get the last available artifact from the previous workflow
          # default false, just try to download from the last one
          check_artifacts: true
          if_no_artifact_found: fail

      - run: ls -lR