name: Publish to Cocoapods

# on:
#   repository_dispatch:
#     types:
#       - cocoapods-deploy
on: 
  push: 
    branches: master

jobs:
  publish:
    name: Download build files and publish to cocoapods
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3
        with:
            token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download and unzip artifact
        run: |
          export RUN_INFO=$(curl -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/aditya-likeminds/LikeMinds-iOS-Feed-SDK/actions/runs)

          export RUN_ID=$(echo $RUN_INFO | jq -r '.workflow_runs[0].id')

          export ARTIFACT_INFO=$(curl -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/aditya-likeminds/LikeMinds-iOS-Feed-SDK/actions/runs/${RUN_ID}/artifacts)

          export ARTIFACT_ID=$(echo $ARTIFACT_INFO | jq -r '.artifacts[0].id')

          curl -LJO -H "Accept: application/vnd.github.v3+json" \
            -H "Authorization: Bearer ${{ secrets.PAT }}" \
            https://api.github.com/repos/aditya-likeminds/LikeMinds-iOS-Feed-SDK/actions/artifacts/${ARTIFACT_ID}/zip

          unzip -qo '*.zip'

          ls -al

      - run: ls -lR